import { RadSideDrawer } from 'nativescript-ui-sidedrawer';
import { NavigationEntry } from 'tns-core-modules/ui/frame/frame';
import { BaseControl } from './BaseControl';
import { IControlData } from './IControlData';
import { SideDrawerObservable } from '../observables/SideDrawerObservable';
export declare class SideDrawer extends BaseControl {
    private _radSideDrawerView;
    private _imageFontIconClassName;
    private _clearHistory;
    private _menuItemDefnsForTabs;
    private _selectedItem;
    private _styles;
    private MENU_ITEM_IMAGE_WIDTH;
    private MENU_ITEM_IMAGE_HEIGHT;
    private HEADER_ICON_HEIGHT;
    private HEADER_ICON_WIDTH;
    private PNG_BASE64_PREFIX;
    initialize(controlData: IControlData): void;
    bind(): Promise<any>;
    renderMainPage(): Promise<NavigationEntry>;
    view(): RadSideDrawer;
    closeDrawer(): void;
    showDrawer(): void;
    private onLoaded;
    private getItemWithIndexPath;
    private getSectionWithIndex;
    private getMenuView;
    getItemsCountPerSection(): number[];
    getSelectedMenuItemIndexPath(): [number, number];
    getSelectedMenuItemName(): string;
    setSelectedMenuItemByName(menuItemName: string): void;
    setSelectedMenuItemByIndexPath(menuItemIndexPath: [number, number]): void;
    getSectionCaptions(): string[];
    setSectionVisibilityAtIndex(sectionIndex: number, visibility: boolean): void;
    getMenuItemCaption(indexPath: [number, number]): string;
    setMenuItemCaption(indexPath: number, caption: string): void;
    setMenuItemVisibility(indexPath: [number, number], visibility: boolean): void;
    redraw(): void;
    protected createObservable(): SideDrawerObservable;
    private getMenuItemIndexFromIndexPath;
    private createDrawer;
    private createSections;
    private createHeader;
    private getHeaderIconTextStyles;
    private setHeaderIconWithTextIcon;
    private createSection;
    private createMenuItem;
    private getClassNameForRtl;
    private readonly isRtl;
    private menuItemSelected;
    private navigateToSelectedItem;
    private navigateToFrame;
    private menuClickedTwice;
    private readonly bottomNavControl;
    private resetMenuItemSelectionState;
    private setMenuItemOnPressStyle;
    private clearMenuItemOnPressStyle;
    private setMenuItemAsActive;
    private resolveData;
    private executeOnPressActionOrRule;
    private getFrameId;
    page(): any;
    private buildNavStackForMenus;
}
