/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package sap.mdkclient;

import com.tns.RuntimeHelper;
import com.tns.Runtime;

@com.tns.JavaScriptImplementation(javaScriptFile = "./application.js")
public class MDKAndroidApplication extends android.app.Application
    implements com.tns.NativeScriptHashCodeProvider {
  private static android.app.Application thiz;

  public MDKAndroidApplication() {
    super();
    thiz = this;
  }

  public void onCreate() {
    com.tns.Runtime runtime = com.tns.RuntimeHelper.initRuntime(this);
    if (!com.tns.Runtime.isInitialized()) {
      try {
        super.onCreate();
        return;
      } catch (Throwable throwable) {
        throw new RuntimeException(throwable);
      }
    }
    java.lang.Object[] args = new java.lang.Object[0];
    com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
    if (runtime != null) {
      runtime.run();
    }
  }

  public void onConfigurationChanged(android.content.res.Configuration param_0) {
    if (!com.tns.Runtime.isInitialized()) {
      try {
        super.onConfigurationChanged(param_0);
        return;
      } catch (Throwable throwable) {
        throw new RuntimeException(throwable);
      }
    }
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    com.tns.Runtime.callJSMethod(this, "onConfigurationChanged", void.class, args);
  }

  protected void attachBaseContext(android.content.Context param_0) {
    if (!com.tns.Runtime.isInitialized()) {
      try {
        super.attachBaseContext(param_0);
        return;
      } catch (Throwable throwable) {
        throw new RuntimeException(throwable);
      }
    }
    java.lang.Object[] args = new java.lang.Object[1];
    args[0] = param_0;
    com.tns.Runtime.callJSMethod(this, "attachBaseContext", void.class, args);
  }

  public static android.app.Application getInstance() {
    return thiz;
  }

  public int hashCode__super() {
    return super.hashCode();
  }

  public boolean equals__super(java.lang.Object other) {
    return super.equals(other);
  }
}
